/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StencilGenerateDemo {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStencilGenerateDemoElement extends Components.StencilGenerateDemo, HTMLStencilElement {
    }
    var HTMLStencilGenerateDemoElement: {
        prototype: HTMLStencilGenerateDemoElement;
        new (): HTMLStencilGenerateDemoElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "stencil-generate-demo": HTMLStencilGenerateDemoElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StencilGenerateDemo {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "stencil-generate-demo": StencilGenerateDemo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "stencil-generate-demo": LocalJSX.StencilGenerateDemo & JSXBase.HTMLAttributes<HTMLStencilGenerateDemoElement>;
        }
    }
}
